spring.application.name=garden-app-garden-engine
server.port=8082

# Mongo Configuration
spring.data.mongodb.uri=${DB_URI}

# RabbitMq
spring.rabbitmq.host=${RABBIT_DEV_HOST}
spring.rabbitmq.port=${RABBIT_DEV_PORT}
spring.rabbitmq.username=${RABBIT_DEV_USERNAME}
spring.rabbitmq.password=${RABBIT_DEV_PASSWORD}
spring.rabbitmq.virtual-host=/

# RabbitMQ exchange/queue/routing key
rabbitmq.exchange=${RABBIT_DEV_EXCHANGE}
rabbitmq.queue=${RABBIT_DEV_QUEUE}
rabbitmq.routing-key=${RABBIT_DEV_ROUTING_KEY}

rabbitmq.audit.exchange=${RABBIT_AUDIT_EXCHANGE}
rabbitmq.audit.queue=${RABBIT_AUDTI_QUEUE}
rabbitmq.audit.routing-key=${RABBIT_AUDIT_ROUTING_KEY}